version: '3.9'

services:

  database:
    image: mariadb:10
    restart: always
    volumes:
      - ./files/healthcheck.cnf:/etc/mysql/healthcheck.cnf:ro
      - ./files/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - LANG=C.UTF-8
      - MARIADB_MYSQL_LOCALHOST_USER=1
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=yeeclass
      - MYSQL_PASSWORD=yeeclass
      - MYSQL_DATABASE=yeeclass
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--defaults-file=/etc/mysql/healthcheck.cnf", "--connect", "--innodb_initialized"]
      interval: 20s
      retries: 10

  web:
    build:
      context: ./
      args:
        TURNSTILE_SITEKEY: 0x4AAAAAAAIvQqkHykLcud99
        TURNSTILE_SECRETKEY: 0x4AAAAAAAIvQg18yY4Tl4WV-PeWCR8DDeM
    environment:
      - FLAG=hitcon{pHp_1s_the_b35t_1ang}
    ports:
      - 8210:80/tcp
    depends_on:
      database:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'running init.php'
        php -f /tmp/init.php
        rm /tmp/init.php
        
        echo 'initialization done, starting apache'
        exec apache2-foreground